mysql:
  host: 127.0.0.1
  port: 3306
  dbname: douyin
  username: root
  password: xxx
  charset: utf8mb4

jwt:
  expire_duration: 3600
  issuer: 'henhenzhuanyibi'
  subject: 'douyin'
  key: 'douyin-tiktok'