server:
  host: 192.168.1.9
  port: 8080
  static: http://192.168.1.9:8080/static/

mysql:
  host: 127.0.0.1
  port: 3306
  dbname: douyin
  username: root
  password: root
  charset: utf8mb4

jwt:
  expire_duration: 3600
  issuer: 'henhenzhuanyibi'
  subject: 'douyin'
  key: 'douyin-tiktok'